solar:
  image: solarproject/solar-celery:f2s
  # path inside of the container should be exactly the same as outside
  # because solar uses absolute path to find resoruce actions files
  volumes:
    - ./solar:/solar
    - ./solard:/solard
    - ./templates:/vagrant/templates
    - ./resources:/vagrant/resources
    - ./f2s:/vagrant/f2s
    - /var/lib/fuel:/var/lib/fuel
    - /etc/fuel/:/etc/fuel
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - RIAK_HOST=riak
    - RIAK_PORT=8087
  # links are not used for configuration because we can rely on non-container
  # based datastores
  links:
    - riak
    - redis

# docker run --name solar -d -v /root/solar/solar:/solar -v /root/solar/solard:/solard -v /root/solar/templates:/vagrant/templates \
# -v /root/solar/resources:/vagrant/resources -v /root/solar/f2s:/vagrant/f2s \
# -v /var/lib/fuel:/var/lib/fuel -v /root/.config/fuel/fuel_client.yaml:/root/.config/fuel/fuel_client.yaml \
# --link=riak:riak --link=redis:redis --name solar solarproject/solar-celery:f2s

riak:
  image: tutum/riak
  ports:
    - 8087:8087
    - 8098:8098
redis:
  image: tutum/redis
  ports:
    - 6379:6379
  environment:
    - REDIS_PASS=**None**
