solar:
  image: solarproject/solar-celery:f2s
  # path inside of the container should be exactly the same as outside
  # because solar uses absolute path to find resoruce actions files
  volumes:
    - ./.vagrant:/vagrant/.vagrant
    - ./solar:/solar
    - ./solard:/solard
    - ./templates:/vagrant/templates
    - ./resources:/vagrant/resources
    - ./f2s:/vagrant/f2s
    - /var/lib/fuel:/var/lib/fuel
    - /etc/fuel/:/etc/fuel
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - RIAK_HOST=riak
    - RIAK_PORT=8087
  # links are not used for configuration because we can rely on non-container
  # based datastores
  links:
    - riak
    - redis
riak:
  image: tutum/riak
  ports:
    - 8087:8087
    - 8098:8098
redis:
  image: tutum/redis
  ports:
    - 6379:6379
  environment:
    - REDIS_PASS=**None**
